export const targetAudienceOptions = [
    { value: "youngProfessionals", label: "Young professionals" },
    { value: "parentsOfYoungChildren", label: "Parents of young children" },
    { value: "collegeStudents", label: "College students" },
    { value: "outdoorEnthusiasts", label: "Outdoor enthusiasts" },
    { value: "techSavvyIndividuals", label: "Tech-savvy individuals" },
    { value: "fitnessWellnessEnthusiasts", label: "Fitness and wellness enthusiasts" },
    { value: "smallBusinessOwners", label: "Small business owners" },
    { value: "petOwners", label: "Pet owners" },
    { value: "fashionConsciousIndividuals", label: "Fashion-conscious individuals" },
    { value: "retireesSeniorCitizens", label: "Retirees and senior citizens" },
    { value: "foodCookingEnthusiasts", label: "Food and cooking enthusiasts" },
    { value: "gamersVideoGameEnthusiasts", label: "Gamers and video game enthusiasts" },
    { value: "adventureTravelers", label: "Adventure travelers" },
    { value: "musicLovers", label: "Music lovers" },
    { value: "environmentalActivists", label: "Environmental activists" },
  ];

  export const timeZoneOptions = [
    { value: "utc", label: "UTC (Coordinated Universal Time)" },
    { value: "gmt", label: "GMT (Greenwich Mean Time)" },
    { value: "est", label: "EST (Eastern Standard Time)" },
    { value: "cst", label: "CST (Central Standard Time)" },
    { value: "mst", label: "MST (Mountain Standard Time)" },
    { value: "pst", label: "PST (Pacific Standard Time)" },
    { value: "ist", label: "IST (Indian Standard Time)" },
    { value: "jst", label: "JST (Japan Standard Time)" },
    { value: "aest", label: "AEST (Australian Eastern Standard Time)" },
    { value: "bst", label: "BST (British Summer Time)" },
    { value: "cet", label: "CET (Central European Time)" },
    { value: "hkt", label: "HKT (Hong Kong Time)" },
    { value: "nzdt", label: "NZDT (New Zealand Daylight Time)" },
    { value: "art", label: "ART (Argentina Time)" },
    { value: "ast", label: "AST (Arabian Standard Time)" },
  ];
  
  export const companySectors = [
    { value: "technology", label: "Technology" },
    { value: "finance", label: "Finance" },
    { value: "healthcare", label: "Healthcare" },
    { value: "retail", label: "Retail" },
    { value: "manufacturing", label: "Manufacturing" },
    { value: "education", label: "Education" },
    { value: "realEstate", label: "Real Estate" },
    { value: "hospitality", label: "Hospitality" },
    { value: "transportation", label: "Transportation" },
    { value: "energy", label: "Energy" },
    { value: "mediaEntertainment", label: "Media and Entertainment" },
    { value: "foodBeverage", label: "Food and Beverage" },
    { value: "automotive", label: "Automotive" },
    { value: "telecommunications", label: "Telecommunications" },
    { value: "nonProfit", label: "Non-profit" },
  ];
  